#
import streamlit as st
import pandas as pd
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from groq import Groq
import urllib.parse

# 1. HARDENED ENTERPRISE CONFIGURATION & SEARCH ENGINE OPTIMIZATION
st.set_page_config(
    page_title="LAW OF AFRICA INTELLIGENCE ENGINE - Premium Legal Portal", 
    page_icon="⚖️", 
    layout="centered",
    initial_sidebar_state="expanded"
)

# Advanced Layout & Input Elements CSS Styling
st.markdown("""
    <style>
    /* Premium Sky Blue Circular Message Send Action Button */
    div.stButton > button:first-child {
        background-color: #A0C3FF !important;
        color: #1E293B !important;
        border: none !important;
        border-radius: 50% !important;
        width: 50px !important;
        height: 50px !important;
        padding: 0px !important;
        display: flex !important;
        align-items: center !important;
        justify-content: center !important;
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.2) !important;
        font-size: 22px !important;
        cursor: pointer;
        transition: transform 0.1s ease-in-out !important;
        margin-top: 0px !important;
    }
    
    div.stButton > button:first-child:hover {
        transform: scale(1.05) !important;
        background-color: #B2D2FF !important;
    }
    
    /* Smooth column container normalization */
    [data-testid="stHorizontalBlock"] {
        align-items: center !important;
    }
    </style>
""", unsafe_allow_html=True)

# Main Structural Titles - Optimized for Google/Safari indexing
st.title("LAW OF AFRICA INTELLIGENCE ENGINE")
st.write("### Welcome to the Official LAW OF AFRICA INTELLIGENCE ENGINE Portal")
st.write("#### *Premium Pan-African Legal Matrix, OHADA Law Brief Generator, and Constitutional History Index.*")
st.success("⚡ **Stop spending 10 hours researching OHADA law. Get a comprehensive, highly accurate legal brief in 10 seconds.**")

with st.expander("🛡️ Data Privacy, Confidentiality & Compliance Framework"):
    st.caption("""
    **Law of Africa Privacy Notice:** All queries processed through this intelligence engine are protected under strict end-to-end cloud encryption. In compliance with pan-African data protection regulations and international privacy protocols, your legal research inputs are entirely isolated, are never cached for external public AI training, and remain entirely confidential to your licensed subscriber session.
    """)
st.divider()

# 2. FIXED EMAIL NOTIFICATION ALERTS ENGINE (SMTP ENTERPRISE GATEWAY)
def trigger_admin_alert(event_type, target_user):
    try:
        admin_recipient = st.secrets["ADMIN_EMAIL"]
        system_sender = st.secrets["SYSTEM_SENDER_EMAIL"]
        system_password = st.secrets["EMAIL_PASSWORD"]
        
        msg = MIMEMultipart()
        msg['From'] = system_sender
        msg['To'] = admin_recipient
        msg['Subject'] = f"Law of Africa Alert: {event_type}"
        
        body_content = f"""
        LAW OF AFRICA SYSTEM SECURITY METRICS
        
        An automated security event has just been tracked on your live engine.
        
        EVENT ACTION: {event_type}
        USER PROFILE: {target_user}
        SYSTEM STATUS: Active & Monitoring
        
        This is an automated alert generated by your cloud infrastructure.
        """
        msg.attach(MIMEText(body_content, 'plain'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(system_sender, system_password)
        server.sendmail(system_sender, admin_recipient, msg.as_string())
        server.quit()
    except Exception:
        pass

# 3. NO-FILE SECRETS DATABASE REFERENCE
try:
    secrets_users = st.secrets["user_accounts"]
    db_df = pd.DataFrame([{"username": k, "password": v, "status": "Premium" if k == "odogwucent" else "Free Trial"} for k, v in secrets_users.items()])
except Exception as e:
    st.error("⚠️ Database Sync Failure: Please configure [user_accounts] inside your Streamlit Secrets.")
    st.stop()

# PERSISTENT SESSION TRACKING & LOGIN REMEMBER LAYER
if "logged_in_user" not in st.session_state:
    st.session_state.logged_in_user = st.experimental_get_query_params().get("user", [None])[0]
if "free_queries_used" not in st.session_state:
    st.session_state.free_queries_used = 0
if "chat_history" not in st.session_state:
    st.session_state.chat_history = [] 

# 4. BACKGROUND VAULT KEY EXTRACTION FOR AI ARCHITECTURE
try:
    groq_api_key = st.secrets["GROQ_API_KEY"]
    ai_client = Groq(api_key=groq_api_key)
except Exception:
    st.error("System Status: Security Vault Keys Missing. Please check your system settings.")
    st.stop()

# YOUR WHATSAPP ADMINISTRATIVE LINK ROUTER
YOUR_WHATSAPP_NUMBER = "234XXXXXXXXXX"  # Change this placeholder to your actual WhatsApp phone number with country code!
ADMIN_EMAIL_ADDRESS = st.secrets.get("ADMIN_EMAIL", "paulinusemmanuel634@gmail.com")

# 5. USER SEGMENTATION & ACCESS GATE (WITH REMEMBER SYSTEM)
if st.session_state.logged_in_user is None:
    st.subheader("🔐 Secure User Portal")
    st.markdown("### Secure Login")
    login_username = st.text_input("Username / Email:").strip()
    login_password = st.text_input("Password:", type="password").strip()
    remember_me = st.checkbox("Keep me logged in on this device 💾", value=True)
    
    if st.button("Log In 🔓", use_container_width=True):
        if db_df.empty:
            st.error("No registered accounts configured in the system.")
        else:
            matched_user = db_df[(db_df['username'].astype(str) == login_username) & (db_df['password'].astype(str) == login_password)]
            
            if not matched_user.empty:
                st.session_state.logged_in_user = login_username
                if remember_me:
                    st.experimental_set_query_params(user=login_username)
                trigger_admin_alert("User Logged In Successfully", login_username)
                st.success(f"Access Granted. Welcome back, {login_username}!")
                st.rerun()
            else:
                st.error("Invalid username or password credentials.")
                
    st.markdown("---")
    st.caption("Don't have an account or having registration layout issues?")
    st.link_button("💬 Chat with Admin Support", f"https://wa.me/{YOUR_WHATSAPP_NUMBER}")
    st.stop()

# 6. APP CONTENT AREA (UNLOCKED UPON SUCCESSFUL LOGIN)
current_user = st.session_state.logged_in_user
user_row = db_df[db_df['username'].astype(str) == current_user]
user_status = user_row['status'].values[0] if not user_row.empty else "Free Trial"

is_premium_user = (user_status == "Premium" or current_user == "odogwucent")

encoded_text = urllib.parse.quote(f"Hello, I am using the Law of Africa Engine as user [{current_user}]. I would like to make a payment and upgrade to the Premium Tier.")
whatsapp_pay_url = f"https://wa.me/{YOUR_WHATSAPP_NUMBER}?text={encoded_text}"

# 7. SYSTEM PAYWALL & SUBSCRIPTION ACCESS MANAGEMENT (STRICT 3-QUERY LIMIT)
MAX_FREE_QUERIES = 3

if not is_premium_user and st.session_state.free_queries_used >= MAX_FREE_QUERIES:
    st.error(f"🛑 Account Status: Evaluation Limit Reached ({MAX_FREE_QUERIES}/{MAX_FREE_QUERIES} queries used). Premium Subscription Required for user [{current_user}].")
    st.markdown("### 🌎 Select Your Jurisdiction & Activate Premium License")
    region = st.radio("Where are you currently practicing law?", ["Select Region...", "Within Africa ($100/mo)", "International (Outside Africa) ($200/mo)"])
    
    if region != "Select Region...":
        st.info(f"🔑 Billing System Notice: Payment gateway request dispatched for {region}.")
        st.markdown("### ⚡ Fast-Track Your Activation:")
        st.write("Click the button below to text the Admin on WhatsApp directly to process your payment and instantly unlock your profile:")
        st.link_button("🟢 Text Admin on WhatsApp to Pay", whatsapp_pay_url)
    
    if st.button("Log Out 🚪", use_container_width=True):
        st.experimental_set_query_params()
        st.session_state.logged_in_user = None
        st.rerun()
    st.stop()

# Profile Tier Metadata Sidebar Banner
st.sidebar.markdown(f"👤 **Active Profile:** `{current_user}`")
st.sidebar.markdown(f"💼 **Account Tier:** `{user_status.upper()}`")
if not is_premium_user:
    st.sidebar.markdown(f"📊 **Free Trials Used:** `{st.session_state.free_queries_used} / {MAX_FREE_QUERIES}`")

# SIDEBAR ADMINISTRATIVE SUPPORT HUB
st.sidebar.markdown("---")
st.sidebar.markdown("### 📞 Help & Account Support")
st.sidebar.write("Need an account upgrade, run into issues, or have payment billing questions?")
st.sidebar.link_button("💬 Chat with Admin via WhatsApp", whatsapp_pay_url)
st.sidebar.link_button("✉️ Send Support Email", f"mailto:{ADMIN_EMAIL_ADDRESS}?subject=Law%20of%20Africa%20Support%20Request&body=User:%20{current_user}")

st.sidebar.markdown("---")
if st.sidebar.button("Log Out 🚪", use_container_width=True):
    st.experimental_set_query_params()
    st.session_state.logged_in_user = None
    st.rerun()

if st.sidebar.button("Reset Application Memory 🔄", use_container_width=True):
    st.experimental_set_query_params()
    st.session_state.clear()
    st.rerun()

# Display ongoing interaction history without the default icons
for chat in st.session_state.chat_history:
    with st.chat_message(chat["role"], avatar="⚖️" if chat["role"] == "assistant" else "👤"):
        st.markdown(chat["content"])

# 8. MATCHED CONVERSATIONAL CHAT INPUT (INLINE CHAT BAR & BLUE CIRCLE BUTTON)
st.markdown("---")
input_col, button_col = st.columns([6, 1])

with input_col:
    user_input = st.text_input(
        "RCS Message Input",
        key="query_input",
        label_visibility="collapsed",
        placeholder="Type your legal or history question here..."
    )

with button_col:
    submit_button = st.button("➤✨")

if submit_button and user_input.strip() != "":
    st.session_state.chat_history.append({"role": "user", "content": user_input})
    
    with st.chat_message("user", avatar="👤"):
        st.markdown(user_input)
        
    with st.chat_message("assistant", avatar="⚖️"):
        response_placeholder = st.empty()
        response_placeholder.markdown("🔍 *Analyzing system matrix and compiling response...*")
        
        try:
            # FIX: Corrected model string spelling to llama-3.3-70b-versatile
            chat_completion = ai_client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "system", 
                        "content": (
                            "You are the premium Law of Africa Intelligence Engine, an elite expert trained in "
                            "African legal frameworks, constitutional architectures, statutory interpretations, case law history, "
                            "and commercial OHADA guidelines. Always provide completely finished, exhaustive legal responses "
                            "divided into neat sections."
                        )
                    },
                    {"role": "user", "content": user_input}
                ],
            )
            ai_response = chat_completion.choices[0].message.content
            response_placeholder.markdown(ai_response)
            st.session_state.chat_history.append({"role": "assistant", "content": ai_response})
            
            if not is_premium_user:
                st.session_state.free_queries_used += 1
            
            st.rerun()
                
        except Exception as e:
            response_placeholder.error(f"⚠️ Engine Sync Error: Please try submitting your request again. Details: {str(e)}")

##
